name: Deploy Recipe Frontend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Загружаем окружение Node/NVM
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            # Переходим в папку проекта
            # Синхронизируем код
            git fetch origin main
            git reset --hard origin/main

            # 3. Установка зависимостей и сборка
            # Используем ci для более быстрой и чистой установки
            npm ci 
            export SITE=https://swageda.ru
            # Можно явно указать HOST и PORT для Astro, чтобы Nginx всегда знал, где искать
            export HOST=127.0.0.1
            export PORT=4321 

            # Временно отключаем проверку SSL для сборки (если Astro делает запросы во время билда)
            export NODE_TLS_REJECT_UNAUTHORIZED=0

            npm run build

            # Перезапуск процесса с ПРАВИЛЬНЫМ именем
            # Мы сначала удаляем старый, чтобы точно убить кэш в памяти
            pm2 delete recipe-frontend || true

            # Запускаем с передачей переменных окружения
            HOST=127.0.0.1 PORT=4321 NODE_ENV=production NODE_TLS_REJECT_UNAUTHORIZED=0 pm2 start dist/server/entry.mjs --name recipe-frontend
            pm2 save

            # 5. Проверка статуса (Healthcheck)
            sleep 5
            pm2 status recipe-frontend
